In [33]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [34]:
df = pd.read_csv(r'/content/Data (1).csv')

In [35]:
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [36]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [37]:
print(x)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [38]:
#for misssing data#
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values = np.nan,strategy = 'mean')#maean of columns#
imp.fit(x[:,1:3])#for salary and age column#
x[:,1:3] = imp.transform(x[:,1:3])

In [39]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [40]:
#Encoding categorical data#
#Enncoding independent variables#
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[0])],remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [41]:
#encoding dependent variable#
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [42]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [43]:
#splitting train-test data#
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test  = train_test_split(x,y,test_size = 0.2,random_state = 5)

In [44]:
print(x_train)

[[0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 0.0 1.0 38.0 61000.0]]


In [45]:
print(y_train)

[0 1 1 1 0 0 0 0]


In [46]:
print(x_test)

[[1.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [47]:
#Feature Scaling#
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#we won't use dummy variables here as they are already in range of -1 to 1#
x_train[:,3:] = sc.fit_transform(x_train[:,3:])
x_test[:,3:] = sc.transform(x_test[:,3:])

In [48]:
x_train

array([[0.0, 1.0, 0.0, -1.2597958529291027, -0.8388998277785314],
       [0.0, 1.0, 0.0, 0.0701939038288944, -0.026540159613350534],
       [1.0, 0.0, 0.0, 1.134185709235292, 1.238156141961987],
       [0.0, 0.0, 1.0, -1.6587927799565019, -1.337393260516256],
       [1.0, 0.0, 0.0, 0.6021898065320932, 0.656580470434642],
       [0.0, 1.0, 0.0, 1.4001836605868916, 1.5704850971204702],
       [0.0, 0.0, 1.0, -0.0923603997748607, -1.0050643053577728],
       [0.0, 0.0, 1.0, -0.19580404752270503, -0.2573241562511862]],
      dtype=object)

In [49]:
x_test

array([[1.0, 0.0, 0.0, -0.32880302319850474, 0.24116927648653827],
       [1.0, 0.0, 0.0, -0.5948009745501042, -0.5065708726200484]],
      dtype=object)